Update build, Take Two
NCAR/notebook-gallery pull request #67
Opened 2021-02-02 23:17 UTC by bonnland

2021-02-02 23:57 UTC, kmpaul requested changes
Commit this and it should run the binderbot action, now.

2021-02-02 23:57 UTC, kmpaul commented on .github/workflows/binderbot.yaml
> +        uses: ad-m/github-push-action@main
This should fix the action.

```suggestion
        uses: ad-m/github-push-action@master
```

2021-02-03 00:06 UTC, bonnland commented
OK, binderbot build is running after that commit.   If it fails, I'm done for today.  I've been confused for many hours and need a break.

2021-02-03 00:11 UTC, bonnland commented
Mentioning https://github.com/pangeo-gallery/pangeo-gallery/pull/48 here in case merging that PR will fix the 500 ISE.

2021-02-03 00:29 UTC, kmpaul commented
Yeah. That seems to be the blocker. Thanks for getting this to this state, @bonnland!

2021-02-03 12:53 UTC, rabernat commented
Once you merge this, things should work.

2021-02-03 13:00 UTC, rabernat commented
> Mentioning [pangeo-gallery/pangeo-gallery#48](https://github.com/pangeo-gallery/pangeo-gallery/pull/48) here in case merging that PR will fix the 500 ISE.

No that is not the right interpretation. This PR needs to be merged FIRST, even with the current binderbot error (which, as I said several times, is ignorable, not something you need to worry about). 

That error comes up because this gallery is not yet part of pangeo-gallery (because pangeo-gallery/pangeo-gallery#48  has not yet been merged). This workflow is trying to trigger a rebuilt action on the pangeo-gallery website, but it's failing because pangeo-gallery doesn't have this repo as a submodule (yet).

However, we can't add the submodule to pangeo-gallery until the binderbot workflow has been _run on the `main` branch` and created a `binderbot-build` branch`. This is the chicken-and-egg situation I referred to.

The solution is to 
1. merge this PR and have binderbot create the `binderbot-built` branch
2. rmerge pangeo-gallery/pangeo-gallery#48  

in that order.

I'm sorry you find this so confusing and that it is causing stress. I offer to meet with you to personally talk you through how binderbot and pangeo-gallery work:
https://calendly.com/ryan-abernathey/15min

2021-02-03 16:43 UTC, bonnland commented
Thanks for the offer; I don't think we need to meet about it after your latest explanation.   I realize these things have some inherent complexity that will seem natural and obvious eventually.

2021-02-03 17:06 UTC, kmpaul approved these changes
Given @rabernat's comment, I approve this merge.  It looks like it's ready.

2021-02-03 18:15 UTC, merged